#!/bin/sh
set -e

if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then
if command -v udevadm >/dev/null 2>&1; then
udevadm control --reload-rules || true
udevadm trigger --subsystem-match=misc --action=change || true
fi
fi

#DEBHELPER#

exit 0
