#!/bin/sh
set -e

if ! getent group linflick >/dev/null 2>&1; then
groupadd --system linflick >/dev/null
fi

if command -v udevadm >/dev/null 2>&1; then
udevadm control --reload-rules || true
udevadm trigger --subsystem-match=misc --action=change || true
fi

#DEBHELPER#

exit 0
